# Website related changes
website:
  - changed-files:
      - any-glob-to-any-file: 'website/**'
      - any-glob-to-any-file: 'package.json'
      - any-glob-to-any-file: 'pnpm-lock.yaml'
      - any-glob-to-any-file: 'pnpm-workspace.yaml'
      - any-glob-to-any-file: '.github/workflows/website.yml'

# Dependencies
dependencies:
  - changed-files:
      - any-glob-to-any-file: 'package.json'
      - any-glob-to-any-file: 'pnpm-lock.yaml'
      - any-glob-to-any-file: 'website/package.json'

# Configuration changes
config:
  - changed-files:
      - any-glob-to-any-file: '.github/**/*'
      - any-glob-to-any-file: '*.config.{js,ts,mjs}'
      - any-glob-to-any-file: 'tsconfig.json'
      - any-glob-to-any-file: '.eslintrc.*'
      - any-glob-to-any-file: '.prettierrc.*'

# Documentation
documentation:
  - changed-files:
      - any-glob-to-any-file: '**/*.md'
      - any-glob-to-any-file: '**/*.mdx'
      - any-glob-to-any-file: 'docs/**/*'

# TypeScript files
typescript:
  - changed-files:
      - any-glob-to-any-file: '**/*.ts'
      - any-glob-to-any-file: '**/*.tsx'
      - any-glob-to-any-file: 'tsconfig.json'

# React components
components:
  - changed-files:
      - any-glob-to-any-file: 'website/src/components/**/*'

# Astro pages/layouts
astro:
  - changed-files:
      - any-glob-to-any-file: 'website/src/pages/**/*.astro'
      - any-glob-to-any-file: 'website/src/layouts/**/*.astro'

# Styles
styles:
  - changed-files:
      - any-glob-to-any-file: '**/*.css'
      - any-glob-to-any-file: '**/*.scss'
      - any-glob-to-any-file: 'tailwind.config.*'

# Testing
testing:
  - changed-files:
      - any-glob-to-any-file: '**/*.test.*'
      - any-glob-to-any-file: '**/*.spec.*'
      - any-glob-to-any-file: 'vitest.config.*'

# CI/CD
ci:
  - changed-files:
      - any-glob-to-any-file: '.github/workflows/**/*'
      - any-glob-to-any-file: '.github/actions/**/*'

# GitHub Actions
github-actions:
  - changed-files:
      - any-glob-to-any-file: '.github/**' 