# name: App CI

# on:
#   push:
#     branches: [main]
#     paths:
#       - 'apps/github-app/**'
#       - 'package.json'
#       - 'pnpm-lock.yaml'
#       - 'pnpm-workspace.yaml'
#       - '.github/workflows/github-app.yml'
#   pull_request:
#     branches: [main]
#     paths:
#       - 'apps/github-app/**'
#       - 'package.json'
#       - 'pnpm-lock.yaml'
#       - 'pnpm-workspace.yaml'
#       - '.github/workflows/github-app.yml'

# jobs:
#   setup:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: pnpm/action-setup@v2
#         with:
#           version: 9.14.4
#       - uses: actions/setup-node@v4
#         with:
#           node-version: 20
#           cache: 'pnpm'
#       - run: pnpm install --frozen-lockfile
#       - uses: actions/cache/save@v3
#         with:
#           path: |
#             node_modules
#             apps/github-app/node_modules
#             **/dist
#           key: ${{ runner.os }}-github-app-${{ hashFiles('**/pnpm-lock.yaml') }}

#   lint:
#     needs: setup
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/cache/restore@v3
#         with:
#           path: |
#             node_modules
#             apps/github-app/node_modules
#             **/dist
#           key: ${{ runner.os }}-github-app-${{ hashFiles('**/pnpm-lock.yaml') }}
#       - run: pnpm --filter @weekly-pr-reports/github-app lint

#   test:
#     needs: setup
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/cache/restore@v3
#         with:
#           path: |
#             node_modules
#             apps/github-app/node_modules
#             **/dist
#           key: ${{ runner.os }}-github-app-${{ hashFiles('**/pnpm-lock.yaml') }}
#       - run: pnpm --filter @weekly-pr-reports/github-app test

#   build:
#     needs: [lint, test]
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/cache/restore@v3
#         with:
#           path: |
#             node_modules
#             apps/github-app/node_modules
#             **/dist
#           key: ${{ runner.os }}-github-app-${{ hashFiles('**/pnpm-lock.yaml') }}
#       - run: pnpm --filter @weekly-pr-reports/github-app build
#       - uses: actions/upload-artifact@v3
#         with:
#           name: github-app-dist
#           path: apps/github-app/dist