name: Labeler

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
    paths:
      - '.github/labeler.yml'
      - '.github/workflows/labeler.yml'
  workflow_dispatch:  # Allow manual trigger
  
permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    name: Label PR
    if: github.event_name == 'pull_request'  # Only run on PRs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Run Labeler
        uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true 